travis:
  secure:
    BINSTAR_TOKEN: SvaRxaRW9s9o9D/bhSBL/huaEvbuFCZmL3q9DQzKW41vdfaoKCar5qT7uqH+4zTyDqiThDQ3t4Jpial3Ax+HhljYnQhvpFz3OEKmUSfAcnEoqlj1tWvPbcGwk9KFAe9HjHcdmNzgVl2I95qOwIMprO+iuWBnThcaCzvSffsMWKLnvQHw+L0DBMEPrhwn3v7rhvaFOlgAw0CgafWjAqxLxKCinawW2bN+Wcx1eDeSVgHMhvRdhu+VSmxkhnRwV0z+lHFKHeYt4cnFFrgyVUABdrtnXfTKi4R+YzuRif7kTYOP19AYnOKVhZQeNew4c2Kepf9Dg0NqJiNx3XNr40i4A9jS1aEBfVZDAg9zGM6KssPWRvDZpt8QhBYsXIWryE9aZQlC82L5FQYyUqiMThEjLUoqBmwIS2okswQn6ABbF2TglXDP9I564Me/MRPIDSZgl12TcnHFIN2ids0XM7Y50Wfq0qS6ftIwcCP3IkBxl5JOsc4CuXSYff+TKewYRcaw/v4B940ZTY3bWs0fJwl6hi4RMB6zhLIgkzuSCP8xBoXAig8uxw+CE3Hdt2g5cZA5JLLaCXYp+UGi8D1ArCm95CCcJ/TTQ/NaMHDmoMpr12RokL/eUjMYgA23VvaEwhA8rPUh2tKrypmOnma5RiirTFwhsTEME4kJo+Vx4oIH1Qs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
